# Generated by Django 4.1.7 on 2023-02-20 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name'], 'verbose_name_plural': 'customer'},
        ),
    ]
