# Generated by Django 4.1.7 on 2023-03-04 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0004_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='typeOfTicketAndPrice',
        ),
    ]
